### ISSUE TITLE
Xbee/Zigbee

### ISSUE THREAD

**Issue by martin9115** [HomeSmartMesh/raspi#15]
Hi, did this part (zigbee/graphview) of the project can work with Xbee/Zigbee?
And it work with Node-red, right?

**Comment by wassfila** [comment]
That's not Node-red, that's simply calling d3-graphvis, then showing a pan zoom of the generated svg.

https://github.com/magjac/d3-graphviz
Demo
https://bl.ocks.org/magjac/4acffdb3afbc4f71b448a210b5060bca

Zigbee2mqtt project developed a collection of link qualities and put them in a grapgh which is used to generate the svg.

You can do the same for any network you just need to know how to create a graph.

But the generated view is a static svg, I created another library that's based on an interactive svg graph
https://github.com/NetworkGraphs/graphysics

I keep gothub issues only for source code dev and bugfixes, if you'd like to know more about the project or get guidance on how to develop something similar, I can offer that in the forum where I collect faq and discussions

https://homesmartmesh.discourse.group/c/webapps/14

**Comment by wassfila** [comment]
@martin9115 I realised that the usage of issue was suggested by the readme, sorry about that, I updated it to reflect redirection to the new website and forum
https://github.com/HomeSmartMesh/raspi#readme
